// Generated by scripts/optimize-media.mjs. Do not edit by hand.
import spatialSoundVideo from "../delivery-media/Desktop images/1_AM_SpatialSound_1x1.mp4";
import spatialSoundVideoPoster from "../delivery-media/Desktop images/1_AM_SpatialSound_1x1.mp4.poster.webp";
import xboxDiscordVideo from "../delivery-media/Desktop images/2_Xbox_DiscordStreamscreen_1x1.mp4";
import xboxDiscordVideoPoster from "../delivery-media/Desktop images/2_Xbox_DiscordStreamscreen_1x1.mp4.poster.webp";
import xbox2030VisionVideo from "../delivery-media/Desktop images/3_Xbox_2030_vision_16x9.mp4";
import xbox2030VisionVideoPoster from "../delivery-media/Desktop images/3_Xbox_2030_vision_16x9.mp4.poster.webp";
import gettyVideo from "../delivery-media/Desktop images/4_GettyUnshuttered_2x3.mp4";
import gettyVideoPoster from "../delivery-media/Desktop images/4_GettyUnshuttered_2x3.mp4.poster.webp";
import gettyRestImage from "../delivery-media/Desktop images/4_GettyUnshuttered_2x3_image.png.webp";
import operaVideo from "../delivery-media/Desktop images/5_Opera_1x1.mp4";
import operaVideoPoster from "../delivery-media/Desktop images/5_Opera_1x1.mp4.poster.webp";
import operaRestImage from "../delivery-media/Desktop images/5_Opera_1x1_image.jpg.webp";
import weekndImage from "../delivery-media/Desktop images/MM_weekend_noLogo.png.webp";
import beyonceVideo from "../delivery-media/Desktop images/Beyonce_NewAlbum_2x3.mp4";
import beyonceVideoPoster from "../delivery-media/Desktop images/Beyonce_NewAlbum_2x3.mp4.poster.webp";
import beyonceYoutubeVideo from "../delivery-media/Beyonce/Beyonce_Youtube_10s.mp4";
import beyonceYoutubeVideoPoster from "../delivery-media/Beyonce/Beyonce_Youtube_10s.mp4.poster.webp";
import beyonceTiktokVideo from "../delivery-media/Beyonce/Beyonce_tiktok_10s.mp4";
import beyonceTiktokVideoPoster from "../delivery-media/Beyonce/Beyonce_tiktok_10s.mp4.poster.webp";
import beyonceMobileVideo from "../delivery-media/Beyonce/Beyonce_mobile_10s.mp4";
import beyonceMobileVideoPoster from "../delivery-media/Beyonce/Beyonce_mobile_10s.mp4.poster.webp";
import huluUpHereVideo from "../delivery-media/Desktop images/Hulu_upHere_16x9.mp4";
import huluUpHereVideoPoster from "../delivery-media/Desktop images/Hulu_upHere_16x9.mp4.poster.webp";
import hboMaxImage from "../delivery-media/Desktop images/HBO_max_heavensGate.png.webp";
import appleTvBaseballVideo1 from "../delivery-media/Apple TV Baseball/Video1.mp4";
import appleTvBaseballVideo1Poster from "../delivery-media/Apple TV Baseball/Video1.mp4.poster.webp";
import appleTvBaseballVideo2 from "../delivery-media/Apple TV Baseball/Video2.mp4";
import appleTvBaseballVideo2Poster from "../delivery-media/Apple TV Baseball/Video2.mp4.poster.webp";
import eltonJohnRestImage from "../delivery-media/Desktop images/EltonJohn_radio_1x1.png.webp";
import eltonJohnImage1 from "../delivery-media/Elton John Radio Show/1.png.webp";
import eltonJohnVideo2 from "../delivery-media/Elton John Radio Show/2.mp4";
import eltonJohnVideo2Poster from "../delivery-media/Elton John Radio Show/2.mp4.poster.webp";
import eltonJohnVideo2Rest9 from "../delivery-media/Elton John Radio Show/2.mp4.poster-9.webp";
import eltonJohnImage3 from "../delivery-media/Elton John Radio Show/3.png.webp";
import eltonJohnImage4 from "../delivery-media/Elton John Radio Show/4.png.webp";
import xboxPcRedesignVideo from "../delivery-media/Desktop images/Xbox_PC_Redesign_16x9.mp4";
import xboxPcRedesignVideoPoster from "../delivery-media/Desktop images/Xbox_PC_Redesign_16x9.mp4.poster.webp";
import xboxCopilotVideo from "../delivery-media/Desktop images/Xbox_copilot_16x9.mp4";
import xboxCopilotVideoPoster from "../delivery-media/Desktop images/Xbox_copilot_16x9.mp4.poster.webp";
import xboxCopilotDetailVideo from "../delivery-media/Xbox Copilot/Main copilot video.mp4";
import xboxCopilotDetailVideoPoster from "../delivery-media/Xbox Copilot/Main copilot video.mp4.poster.webp";
import xboxCopilotImage1 from "../delivery-media/Xbox Copilot/Image1_00000.png.webp";
import xboxCopilotImage2 from "../delivery-media/Xbox Copilot/Image2_00000.png.webp";
import xboxCopilotImage3 from "../delivery-media/Xbox Copilot/Image3_00000.png.webp";
import xboxCopilotImage4 from "../delivery-media/Xbox Copilot/Image4_00000.png.webp";
import xboxCopilotImage5 from "../delivery-media/Xbox Copilot/Image5_00000.png.webp";
import xboxCopilotImage6 from "../delivery-media/Xbox Copilot/Image6_00000.png.webp";
import xboxCopilotImage7 from "../delivery-media/Xbox Copilot/Image7_00000.png.webp";
import xboxCopilotImage8 from "../delivery-media/Xbox Copilot/Image8_00000.png.webp";
import xboxCopilotImage9 from "../delivery-media/Xbox Copilot/Image9_00000.png.webp";
import xboxCopilotImage10 from "../delivery-media/Xbox Copilot/Image10_00000.png.webp";
import navigationIntroVideo from "../delivery-media/Desktop images/Navigation_intro.mp4";
import navigationIntroVideoPoster from "../delivery-media/Desktop images/Navigation_intro.mp4.poster.webp";
import navigationIntroDetailVideo from "../delivery-media/Single videos/Navigation_intro.mp4";
import navigationIntroDetailVideoPoster from "../delivery-media/Single videos/Navigation_intro.mp4.poster.webp";
import desktopNavigationImage from "../delivery-media/Navigation/Desktop_nav.png.webp";
import desktopNavigationImage_640 from "../delivery-media/Navigation/Desktop_nav.png.webp.640w.webp";
import desktopNavigationImage_1280 from "../delivery-media/Navigation/Desktop_nav.png.webp.1280w.webp";
import xboxModeLowDensityImage from "../delivery-media/Navigation/Xbox mode Low density.png.webp";
import xboxModeLowDensityImage_640 from "../delivery-media/Navigation/Xbox mode Low density.png.webp.640w.webp";
import xboxModeLowDensityImage_1280 from "../delivery-media/Navigation/Xbox mode Low density.png.webp.1280w.webp";
import xboxModeLowDensityImage_1920 from "../delivery-media/Navigation/Xbox mode Low density.png.webp.1920w.webp";
import xboxModeLowDensityImage_2560 from "../delivery-media/Navigation/Xbox mode Low density.png.webp.2560w.webp";
import desktopModeHighDensityImage from "../delivery-media/Navigation/Desktop mode high density.png.webp";
import desktopModeHighDensityImage_640 from "../delivery-media/Navigation/Desktop mode high density.png.webp.640w.webp";
import desktopModeHighDensityImage_1280 from "../delivery-media/Navigation/Desktop mode high density.png.webp.1280w.webp";
import desktopModeHighDensityImage_1920 from "../delivery-media/Navigation/Desktop mode high density.png.webp.1920w.webp";
import desktopModeHighDensityImage_2560 from "../delivery-media/Navigation/Desktop mode high density.png.webp.2560w.webp";
import operaDetailVideo from "../delivery-media/Opera/Opera_1.mp4";
import operaDetailVideoPoster from "../delivery-media/Opera/Opera_1.mp4.poster.webp";
import operaSecondDetailVideo from "../delivery-media/Opera/Opera_2.mp4";
import operaSecondDetailVideoPoster from "../delivery-media/Opera/Opera_2.mp4.poster.webp";
import operaThirdDetailVideo from "../delivery-media/Opera/Opera 3.mp4";
import operaThirdDetailVideoPoster from "../delivery-media/Opera/Opera 3.mp4.poster.webp";
import gettyDetailImage1 from "../delivery-media/Getty/Image1.jpg.webp";
import gettyDetailImage2 from "../delivery-media/Getty/Image2.jpg.webp";
import gettyDetailImage3 from "../delivery-media/Getty/Image3.jpg.webp";
import gettyDetailImage4 from "../delivery-media/Getty/Image4.jpg.webp";
import gettyDetailImage6 from "../delivery-media/Getty/Image6.jpg.webp";
import gettyDetailImage7 from "../delivery-media/Getty/Image7.jpg.webp";
import gettyDetailImage8 from "../delivery-media/Getty/Image8.jpg.webp";
import gettyDetailImage9 from "../delivery-media/Getty/Image9.jpg.webp";
import gettyDetailImage10 from "../delivery-media/Getty/Image10.jpg.webp";
import gettyDetailVideo from "../delivery-media/Getty/Getty video_1.mp4";
import gettyDetailVideoPoster from "../delivery-media/Getty/Getty video_1.mp4.poster.webp";
import gettyFountainSquareVideo from "../delivery-media/Getty/Fountain_Sq.mp4";
import gettyFountainSquareVideoPoster from "../delivery-media/Getty/Fountain_Sq.mp4.poster.webp";
import altCtrlYeahYeahYeahsVideo from "../delivery-media/AM_T1_playlists/ALT_CNTRL_YeahYeahYeahs_16x9.mp4";
import altCtrlYeahYeahYeahsVideoPoster from "../delivery-media/AM_T1_playlists/ALT_CNTRL_YeahYeahYeahs_16x9.mp4.poster.webp";
import altCtrlYeahYeahYeahsDetailVideo from "../delivery-media/AM_T1_playlists/ALT_CNTRL_YeahYeahYeahs_21x9.mp4";
import altCtrlYeahYeahYeahsDetailVideoPoster from "../delivery-media/AM_T1_playlists/ALT_CNTRL_YeahYeahYeahs_21x9.mp4.poster.webp";
import dalePlayRosaliaDetailVideo from "../delivery-media/AM_T1_playlists/Dale-play-rosalia_21x9.mp4";
import dalePlayRosaliaDetailVideoPoster from "../delivery-media/AM_T1_playlists/Dale-play-rosalia_21x9.mp4.poster.webp";
import dxl03Video from "../delivery-media/AM_T1_playlists/DXL_03.mp4";
import dxl03VideoPoster from "../delivery-media/AM_T1_playlists/DXL_03.mp4.poster.webp";
import dxl03VideoRest6 from "../delivery-media/AM_T1_playlists/DXL_03.mp4.poster-6.webp";
import dxl04Video from "../delivery-media/AM_T1_playlists/DXL_04.mp4";
import dxl04VideoPoster from "../delivery-media/AM_T1_playlists/DXL_04.mp4.poster.webp";
import dxl04VideoRest6 from "../delivery-media/AM_T1_playlists/DXL_04.mp4.poster-6.webp";
import aListPopDuaLipaVideo from "../delivery-media/AM_T1_playlists/A_list_pop_DuaLipa_1x1.mp4";
import aListPopDuaLipaVideoPoster from "../delivery-media/AM_T1_playlists/A_list_pop_DuaLipa_1x1.mp4.poster.webp";
import superbloomGothBabeVideo from "../delivery-media/AM_T1_playlists/Superbloom_GothBabe_1x1.mp4";
import superbloomGothBabeVideoPoster from "../delivery-media/AM_T1_playlists/Superbloom_GothBabe_1x1.mp4.poster.webp";
import todaysCountryVideo from "../delivery-media/AM_T1_playlists/Todays_Country_1x1.mp4";
import todaysCountryVideoPoster from "../delivery-media/AM_T1_playlists/Todays_Country_1x1.mp4.poster.webp";
import rapLifeVideo from "../delivery-media/AM_T1_playlists/Rap_life_1x1.mp4";
import rapLifeVideoPoster from "../delivery-media/AM_T1_playlists/Rap_life_1x1.mp4.poster.webp";
import dxl01Video from "../delivery-media/AM_T1_playlists/DXL_01.mp4";
import dxl01VideoPoster from "../delivery-media/AM_T1_playlists/DXL_01.mp4.poster.webp";
import dxl01VideoRest6 from "../delivery-media/AM_T1_playlists/DXL_01.mp4.poster-6.webp";
import nmd03Video from "../delivery-media/AM_T1_playlists/NMD_03.mp4";
import nmd03VideoPoster from "../delivery-media/AM_T1_playlists/NMD_03.mp4.poster.webp";
import nmd03VideoRest6 from "../delivery-media/AM_T1_playlists/NMD_03.mp4.poster-6.webp";
import xbox2030DetailVideo from "../delivery-media/Single videos/Xbox 2030 vision.mp4";
import xbox2030DetailVideoPoster from "../delivery-media/Single videos/Xbox 2030 vision.mp4.poster.webp";
import xboxDiscordDetailVideo from "../delivery-media/Single videos/Discord x Xbox.mp4";
import xboxDiscordDetailVideoPoster from "../delivery-media/Single videos/Discord x Xbox.mp4.poster.webp";
import xboxDiscord2DVideo from "../delivery-media/Single videos/Discord x Xbox - 2D.mp4";
import xboxDiscord2DVideoPoster from "../delivery-media/Single videos/Discord x Xbox - 2D.mp4.poster.webp";
import xboxPcAfterImage1 from "../delivery-media/Xbox PC app/After Image 1.png.webp";
import xboxPcBeforeImage1 from "../delivery-media/Xbox PC app/Before 1.png.webp";
import xboxPcAfterImage2 from "../delivery-media/Xbox PC app/After image 2.png.webp";
import xboxPcBeforeImage2 from "../delivery-media/Xbox PC app/Befroe 2.png.webp";
import xboxPcAfterImage3 from "../delivery-media/Xbox PC app/After Image 3.png.webp";
import xboxPcBeforeImage3 from "../delivery-media/Xbox PC app/Before 3.png.webp";
import xboxPcAfterImage4 from "../delivery-media/Xbox PC app/After Image 4.png.webp";
import anittaNycVideo from "../delivery-media/AM_Spatial sound/Anitta_NYC.mp4";
import anittaNycVideoPoster from "../delivery-media/AM_Spatial sound/Anitta_NYC.mp4.poster.webp";
import zeddMobileVideo from "../delivery-media/AM_Spatial sound/Zedd_Mobile.mp4";
import zeddMobileVideoPoster from "../delivery-media/AM_Spatial sound/Zedd_Mobile.mp4.poster.webp";
import zeddNycVideo from "../delivery-media/AM_Spatial sound/Zedd_NYC.mp4";
import zeddNycVideoPoster from "../delivery-media/AM_Spatial sound/Zedd_NYC.mp4.poster.webp";

export const videoMetadata: Record<string, { poster: string; width: number; height: number; restPosters?: Record<number, string> }> = {
  [spatialSoundVideo]: { poster: spatialSoundVideoPoster, width: 500, height: 500 },
  [xboxDiscordVideo]: { poster: xboxDiscordVideoPoster, width: 500, height: 500 },
  [xbox2030VisionVideo]: { poster: xbox2030VisionVideoPoster, width: 960, height: 540 },
  [gettyVideo]: { poster: gettyVideoPoster, width: 640, height: 960 },
  [operaVideo]: { poster: operaVideoPoster, width: 960, height: 960 },
  [beyonceVideo]: { poster: beyonceVideoPoster, width: 640, height: 960 },
  [beyonceYoutubeVideo]: { poster: beyonceYoutubeVideoPoster, width: 1920, height: 1080 },
  [beyonceTiktokVideo]: { poster: beyonceTiktokVideoPoster, width: 1080, height: 1920 },
  [beyonceMobileVideo]: { poster: beyonceMobileVideoPoster, width: 1080, height: 1920 },
  [huluUpHereVideo]: { poster: huluUpHereVideoPoster, width: 960, height: 540 },
  [appleTvBaseballVideo1]: { poster: appleTvBaseballVideo1Poster, width: 1920, height: 1242 },
  [appleTvBaseballVideo2]: { poster: appleTvBaseballVideo2Poster, width: 1920, height: 1242 },
  [eltonJohnVideo2]: { poster: eltonJohnVideo2Poster, width: 1080, height: 1080, restPosters: { 9: eltonJohnVideo2Rest9 } },
  [xboxPcRedesignVideo]: { poster: xboxPcRedesignVideoPoster, width: 960, height: 540 },
  [xboxCopilotVideo]: { poster: xboxCopilotVideoPoster, width: 960, height: 540 },
  [xboxCopilotDetailVideo]: { poster: xboxCopilotDetailVideoPoster, width: 1920, height: 1080 },
  [navigationIntroVideo]: { poster: navigationIntroVideoPoster, width: 1920, height: 1080 },
  [navigationIntroDetailVideo]: { poster: navigationIntroDetailVideoPoster, width: 1920, height: 1080 },
  [operaDetailVideo]: { poster: operaDetailVideoPoster, width: 1920, height: 1080 },
  [operaSecondDetailVideo]: { poster: operaSecondDetailVideoPoster, width: 1920, height: 1080 },
  [operaThirdDetailVideo]: { poster: operaThirdDetailVideoPoster, width: 1920, height: 1080 },
  [gettyDetailVideo]: { poster: gettyDetailVideoPoster, width: 1080, height: 1080 },
  [gettyFountainSquareVideo]: { poster: gettyFountainSquareVideoPoster, width: 1876, height: 1920 },
  [altCtrlYeahYeahYeahsVideo]: { poster: altCtrlYeahYeahYeahsVideoPoster, width: 960, height: 540 },
  [altCtrlYeahYeahYeahsDetailVideo]: { poster: altCtrlYeahYeahYeahsDetailVideoPoster, width: 1920, height: 824 },
  [dalePlayRosaliaDetailVideo]: { poster: dalePlayRosaliaDetailVideoPoster, width: 1920, height: 824 },
  [dxl03Video]: { poster: dxl03VideoPoster, width: 1920, height: 1920, restPosters: { 6: dxl03VideoRest6 } },
  [dxl04Video]: { poster: dxl04VideoPoster, width: 1920, height: 1920, restPosters: { 6: dxl04VideoRest6 } },
  [aListPopDuaLipaVideo]: { poster: aListPopDuaLipaVideoPoster, width: 1920, height: 1920 },
  [superbloomGothBabeVideo]: { poster: superbloomGothBabeVideoPoster, width: 1920, height: 1920 },
  [todaysCountryVideo]: { poster: todaysCountryVideoPoster, width: 1920, height: 1920 },
  [rapLifeVideo]: { poster: rapLifeVideoPoster, width: 1920, height: 1920 },
  [dxl01Video]: { poster: dxl01VideoPoster, width: 1920, height: 1920, restPosters: { 6: dxl01VideoRest6 } },
  [nmd03Video]: { poster: nmd03VideoPoster, width: 1920, height: 1920, restPosters: { 6: nmd03VideoRest6 } },
  [xbox2030DetailVideo]: { poster: xbox2030DetailVideoPoster, width: 1920, height: 1080 },
  [xboxDiscordDetailVideo]: { poster: xboxDiscordDetailVideoPoster, width: 1920, height: 1080 },
  [xboxDiscord2DVideo]: { poster: xboxDiscord2DVideoPoster, width: 1920, height: 1080 },
  [anittaNycVideo]: { poster: anittaNycVideoPoster, width: 1920, height: 1080 },
  [zeddMobileVideo]: { poster: zeddMobileVideoPoster, width: 1080, height: 1920 },
  [zeddNycVideo]: { poster: zeddNycVideoPoster, width: 1920, height: 1080 },
};

export const imageMetadata: Record<string, { width: number; height: number; srcSet?: string }> = {
  [gettyRestImage]: { width: 848, height: 1264 },
  [operaRestImage]: { width: 1080, height: 1080 },
  [weekndImage]: { width: 1254, height: 1254 },
  [hboMaxImage]: { width: 2560, height: 1070 },
  [eltonJohnRestImage]: { width: 1080, height: 1080 },
  [eltonJohnImage1]: { width: 1080, height: 1080 },
  [eltonJohnImage3]: { width: 1080, height: 1080 },
  [eltonJohnImage4]: { width: 1080, height: 1080 },
  [xboxCopilotImage1]: { width: 1920, height: 1080 },
  [xboxCopilotImage2]: { width: 1920, height: 1080 },
  [xboxCopilotImage3]: { width: 1920, height: 1080 },
  [xboxCopilotImage4]: { width: 1920, height: 1080 },
  [xboxCopilotImage5]: { width: 1920, height: 1080 },
  [xboxCopilotImage6]: { width: 1920, height: 1080 },
  [xboxCopilotImage7]: { width: 1920, height: 1080 },
  [xboxCopilotImage8]: { width: 1920, height: 1080 },
  [xboxCopilotImage9]: { width: 1920, height: 1080 },
  [xboxCopilotImage10]: { width: 1920, height: 1080 },
  [desktopNavigationImage]: { width: 1827, height: 1041, srcSet: [desktopNavigationImage_640 + " 640w", desktopNavigationImage_1280 + " 1280w", desktopNavigationImage + " 1827w"].join(", ") },
  [xboxModeLowDensityImage]: { width: 3840, height: 2162, srcSet: [xboxModeLowDensityImage_640 + " 640w", xboxModeLowDensityImage_1280 + " 1280w", xboxModeLowDensityImage_1920 + " 1920w", xboxModeLowDensityImage_2560 + " 2560w", xboxModeLowDensityImage + " 3840w"].join(", ") },
  [desktopModeHighDensityImage]: { width: 3840, height: 2160, srcSet: [desktopModeHighDensityImage_640 + " 640w", desktopModeHighDensityImage_1280 + " 1280w", desktopModeHighDensityImage_1920 + " 1920w", desktopModeHighDensityImage_2560 + " 2560w", desktopModeHighDensityImage + " 3840w"].join(", ") },
  [gettyDetailImage1]: { width: 2560, height: 1920 },
  [gettyDetailImage2]: { width: 2560, height: 1920 },
  [gettyDetailImage3]: { width: 2560, height: 1707 },
  [gettyDetailImage4]: { width: 2560, height: 1707 },
  [gettyDetailImage6]: { width: 2560, height: 1440 },
  [gettyDetailImage7]: { width: 2560, height: 1440 },
  [gettyDetailImage8]: { width: 2560, height: 1440 },
  [gettyDetailImage9]: { width: 2560, height: 2560 },
  [gettyDetailImage10]: { width: 1280, height: 1265 },
  [xboxPcAfterImage1]: { width: 2560, height: 1836 },
  [xboxPcBeforeImage1]: { width: 2560, height: 1836 },
  [xboxPcAfterImage2]: { width: 2560, height: 1836 },
  [xboxPcBeforeImage2]: { width: 2560, height: 1836 },
  [xboxPcAfterImage3]: { width: 2560, height: 1836 },
  [xboxPcBeforeImage3]: { width: 2560, height: 1836 },
  [xboxPcAfterImage4]: { width: 2560, height: 1836 },
};
